---
- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes

- name: Join Kubernetes cluster
  shell: kubeadm join 192.168.50.10:6443 \
          --token={{ kubeadm_token }} \
          --discovery-token-unsafe-skip-ca-verification