---
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - docker
    - kubernetes/master
    - cni

- hosts: nodes
  gather_facts: yes
  become: yes
  roles:
    - docker
    - kubernetes/node
