---
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - cri/docker
    - kubernetes/master
    - cni/calico

- hosts: nodes
  gather_facts: yes
  become: yes
  roles:
    - cri/docker
    - kubernetes/node
