---
- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: kubeadm init \
          --pod-network-cidr=10.244.0.0/16
          --token={{ kubeadm_token }}
  register: init_cluster

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true

- name: Deploy kubernetes dashboard into cluster
  when: init_cluster is succeeded
  become: false
  shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
  register: dashboard
  until: dashboard.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true