---
- name: Install docker dependencies
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']

- name: Add docker repository
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install docker
  yum: 
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: installed
  register: docker_installed

- name: Start docker
  when: docker_installed is succeeded
  systemd: 
    name: docker 
    state: restarted
    daemon_reload: yes
    enabled: yes