---
- name: Install docker dependencies
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']

- name: Add docker repository
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Installs docker
  yum: 
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: installed
  notify: Start docker